### ISSUE TITLE
Hi Sara

### ISSUE THREAD

**Issue by hunyukun** [polimi-ispl/TIFS2019-stabilized-video-attribution#2]
Hi Sara,

I'm reading the paper Facing Device Attribution Problem for Stabilized Video Sequences, and feel confused about the implemetation. I'm wondering whether the source code is available and it will be very kind of you if you might upload the source code or email it to me. Here is my email adress: linkmao@foxmail.com or lm1173803065@gmail.com
Thanks
kunmao

**Comment by smandelli** [comment]
Dear @hunyukun,

The paper code is already uploaded in this repository. 
You can run the script [compute_Kv.m](https://github.com/polimi-ispl/TIFS2019-stabilized-video-attribution/blob/master/compute_Kv.m) to generate the video fingerprint using only the video frames, and then you can test a new query video by running [test_query_video.m](https://github.com/polimi-ispl/TIFS2019-stabilized-video-attribution/blob/master/test_query_video.m). You can find all the details in the README.
Let me know if you find any issues understanding the scripts

Best,

Sara
